# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('snow_name', models.CharField(max_length=100)),
                ('email', models.CharField(help_text='E-mail distribution list', max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('ciso', models.ForeignKey(help_text='chief information security officer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciso', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('technical_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_contact', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('auth.group',),
        ),
    ]
