# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='team',
            field=models.ForeignKey(help_text="Assest's team owner", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='organization.Team'),
        ),
        migrations.AddField(
            model_name='host',
            name='application_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='organization.Team'),
        ),
        migrations.AddField(
            model_name='host',
            name='system_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system', to='organization.Team'),
        ),
    ]
