# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170625_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='machine_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='geo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Geo'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Host'),
        ),
    ]
