# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_host_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='vm_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
