# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_edit_host_vm_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mac_address', models.CharField(max_length=18)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='inventory.Host')),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_address', to='inventory.Interface')),
            ],
        ),
        migrations.RemoveField(
            model_name='netinterface',
            name='host',
        ),
        migrations.RemoveField(
            model_name='netipaddress',
            name='interface',
        ),
        migrations.AlterField(
            model_name='domainname',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_names', to='inventory.IPAddress'),
        ),
        migrations.DeleteModel(
            name='NetInterface',
        ),
        migrations.DeleteModel(
            name='NetIPAddress',
        ),
    ]
