# Generated by Django 2.0.3 on 2018-03-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_netobjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='geo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Geo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='team',
            field=models.ForeignKey(help_text="Assest's team owner", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset', to='organization.Team'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_names', to='inventory.IPAddress'),
        ),
        migrations.AlterField(
            model_name='host',
            name='application_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application', to='organization.Team'),
        ),
        migrations.AlterField(
            model_name='host',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Domain'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hardware_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.HardwareType'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.OSDistribution'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_distribution_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.OSDistributionVersion'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.OSFamily'),
        ),
        migrations.AlterField(
            model_name='host',
            name='parent_host',
            field=models.ForeignKey(help_text='VM parent host', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest', to='inventory.Host'),
        ),
        migrations.AlterField(
            model_name='host',
            name='system_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system', to='organization.Team'),
        ),
    ]
