# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('snow_id', models.CharField(help_text='ServiceNow database ID', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='partially qualified domain name', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mac_address', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='NetIPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmapi.NetInterface')),
            ],
        ),
        migrations.CreateModel(
            name='OSDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OSDistributionMajorVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('version', models.IntegerField()),
                ('os_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmapi.OSDistribution')),
            ],
        ),
        migrations.CreateModel(
            name='OSDistributionVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=5)),
                ('os_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmapi.OSDistribution')),
                ('os_distribution_major_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmapi.OSDistributionMajorVersion')),
            ],
        ),
        migrations.CreateModel(
            name='OSFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pmapi.Asset')),
                ('local_name', models.CharField(max_length=30)),
                ('dns_name', models.CharField(max_length=255)),
                ('vm_name', models.CharField(max_length=30)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmapi.Domain')),
                ('hardware_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmapi.HardwareType')),
            ],
            bases=('pmapi.asset',),
        ),
        migrations.AddField(
            model_name='osdistribution',
            name='os_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmapi.OSFamily'),
        ),
        migrations.AddField(
            model_name='domainname',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmapi.NetIPAddress'),
        ),
        migrations.AddField(
            model_name='asset',
            name='geo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmapi.Geo'),
        ),
        migrations.AlterUniqueTogether(
            name='osdistributionversion',
            unique_together=set([('os_distribution', 'version'), ('os_distribution_major_version', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='osdistributionmajorversion',
            unique_together=set([('os_distribution', 'version')]),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmapi.Host'),
        ),
        migrations.AddField(
            model_name='host',
            name='os_distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmapi.OSDistribution'),
        ),
        migrations.AddField(
            model_name='host',
            name='os_distribution_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmapi.OSDistributionVersion'),
        ),
        migrations.AddField(
            model_name='host',
            name='os_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmapi.OSFamily'),
        ),
        migrations.AddField(
            model_name='host',
            name='parent_host',
            field=models.ForeignKey(help_text='VM parent host', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='pmapi.Host'),
        ),
    ]
